Q1. Write a Numpy program to get the Numpy version. 

In [2]:
import numpy as np
print(np.__version__)

1.23.5


Q2. Write a NumPy program to test whether none of the elements of a given array are zero

In [5]:
import numpy as np
x = np.array([1, 2, 3, 4,])
print(x)
print(np.all(x))



[1 2 3 4]
True


Q3. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [6]:
import numpy as np
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


Q4. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array

In [7]:
import numpy as np
X = np.array([1, 7, 13, 105])
print("Original array:")
print(X)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize))

Original array:
[  1   7  13 105]
Size of the memory occupied by the said array:
16 bytes


Q5. Write a NumPy program to create an array of integers from 30 to 70.

In [8]:
import numpy as np
array=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70")
print(array) 

Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


Q6. Write a NumPy program to create an array of all even integers from 30 to 70.

In [9]:
import numpy as np
array=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70")
print(array)

Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


Q7.  Write a NumPy program to create a 3x3 identity matrix.

In [11]:
import numpy as np
array=np.identity(3)
print('3x3 matrix:')
print(array)


3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q8.  Write a search NumPy program to create a 3X4 array and iterate over it.

In [13]:
import numpy as np
array=np.identity(4)
print('3x4 matrix:')
print(array)


3x4 matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
